GET http://localhost:3000/

###

GET http://localhost:3000/posts

###

POST http://localhost:3000/posts/new-thread/
Content-Type: application/json

{
    "title":"Title sent",
    "body":"body is here, more and more words"
}

###

POST http://localhost:5000/auth/signupwithgoogle
Content-Type: application/json

{
    "tokenId": "asdjf;ladsfkjbasvlkahs;hewo;haskas"
}

###

POST http://localhost:5000/auth/signupwithgoogle
Content-Type: application/json

{

}